// <auto-generated />
using ComputerNetwork.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputerNetwork.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190717122835_migrations")]
    partial class migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputerNetwork.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfAdd");

                    b.Property<string>("Gateway")
                        .HasMaxLength(15);

                    b.Property<string>("IdOfElement")
                        .IsRequired();

                    b.Property<string>("Image");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Label");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("NameOfElement")
                        .IsRequired();

                    b.Property<string>("NameOfNetwork");

                    b.Property<string>("Shape");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("ComputerNetwork.Models.Edge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfAdd");

                    b.Property<string>("From");

                    b.Property<string>("NameOfNetwork");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("ComputerNetwork.Models.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfAdd");

                    b.Property<string>("NameOfNetwork");

                    b.HasKey("Id");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("ComputerNetwork.Models.Router", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfAdd");

                    b.Property<string>("Gateway")
                        .HasMaxLength(15);

                    b.Property<string>("IdOfElement")
                        .IsRequired();

                    b.Property<string>("Image");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Label");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("NameOfElement")
                        .IsRequired();

                    b.Property<string>("NameOfNetwork");

                    b.Property<string>("Shape");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Routers");
                });

            modelBuilder.Entity("ComputerNetwork.Models.Switch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateOfAdd");

                    b.Property<string>("Gateway")
                        .HasMaxLength(15);

                    b.Property<string>("IdOfElement")
                        .IsRequired();

                    b.Property<string>("Image");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Label");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("NameOfElement")
                        .IsRequired();

                    b.Property<string>("NameOfNetwork");

                    b.Property<string>("Shape");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Switches");
                });
#pragma warning restore 612, 618
        }
    }
}
